-- Insert data into ccachiuser table
INSERT INTO board (contents, title, user_id, url) VALUES
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10'),
                                                      ('Board 1 Contents', 'Board 1 Title', 1, 'url1'),
                                                      ('Board 2 Contents', 'Board 2 Title', 2, 'url2'),
                                                      ('Board 3 Contents', 'Board 3 Title', 3, 'url3'),
                                                      ('Board 4 Contents', 'Board 4 Title', 4, 'url4'),
                                                      ('Board 5 Contents', 'Board 5 Title', 5, 'url5'),
                                                      ('Board 6 Contents', 'Board 6 Title', 1, 'url6'),
                                                      ('Board 7 Contents', 'Board 7 Title', 2, 'url7'),
                                                      ('Board 8 Contents', 'Board 8 Title', 3, 'url8'),
                                                      ('Board 9 Contents', 'Board 7 Title', 4, 'url9'),
                                                      ('Board 10 Contents', 'Board 8 Title', 5, 'url10');


-- Insert data into comment table for random boards
INSERT INTO comment (content, board_id, user_id) VALUES
-- Repeat the following block for each of the 300 comments
    ('Comment 1', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment 2', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1),
    ('Comment 300', FLOOR(RAND() * 137) + 1, FLOOR(RAND() * 5) + 1);

-- Insert data into board table for each user
INSERT INTO ccachiuser (email, password, name) VALUES
                                                   ('user5@example.com', 'password5', 'User 5');


UPDATE board
SET comment_count = (
    SELECT COUNT(*)
    FROM comment
    WHERE comment.board_id = board.id
)
WHERE id IN (
    SELECT DISTINCT board_id
    FROM comment
);
